apiVersion: v1
kind: Service
metadata:
  labels:
    role: web
  name: dev-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: web
  name: dev-web
spec:
  replicas: 2
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
    spec:
      containers:
      - image: nginx
        name: web
